#!/usr/bin/env node
/**
 * Contract drift check (architecture §35 / CI gate 7).
 *
 * 1. Re-export OpenAPI from FastAPI into a temp file and diff against the
 *    committed packages/contracts/openapi.json.
 * 2. Re-generate TypeScript from the committed OpenAPI and diff against
 *    packages/contracts/generated/schema.ts.
 *
 * Usage (repo root): node packages/contracts/scripts/check.mjs
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(PACKAGE_ROOT, '../..');
const API_ROOT = path.join(REPO_ROOT, 'apps', 'api');
const OPENAPI_PATH = path.join(PACKAGE_ROOT, 'openapi.json');
const SCHEMA_PATH = path.join(PACKAGE_ROOT, 'generated', 'schema.ts');
const require = createRequire(import.meta.url);

const GENERATED_BANNER =
  '/**\n' +
  ' * Generated by `make contracts` from packages/contracts/openapi.json.\n' +
  ' * Do not edit by hand.\n' +
  ' */\n\n';

function fail(message) {
  console.error(message);
  process.exit(1);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    encoding: 'utf8',
    ...options,
  });
  if (result.status !== 0) {
    const detail = (result.stderr || result.stdout || '').trim();
    fail(
      `Command failed (${command} ${args.join(' ')})${detail ? `:\n${detail}` : ''}`,
    );
  }
  return result;
}

function normalizeNewlines(text) {
  return text.replace(/\r\n/g, '\n');
}

function resolveOpenapiTypescriptBin() {
  try {
    const pkgJson = require.resolve('openapi-typescript/package.json', {
      paths: [PACKAGE_ROOT],
    });
    const pkg = JSON.parse(fs.readFileSync(pkgJson, 'utf8'));
    const binRel = typeof pkg.bin === 'string' ? pkg.bin : pkg.bin['openapi-typescript'];
    return path.join(path.dirname(pkgJson), binRel);
  } catch {
    return null;
  }
}

function applyBanner(body) {
  if (!body.startsWith('/**\n * Generated by `make contracts`')) {
    return GENERATED_BANNER + body;
  }
  return body;
}

function main() {
  if (!fs.existsSync(OPENAPI_PATH)) {
    fail(`Missing committed OpenAPI at ${OPENAPI_PATH}. Run make contracts.`);
  }
  if (!fs.existsSync(SCHEMA_PATH)) {
    fail(`Missing generated types at ${SCHEMA_PATH}. Run make contracts.`);
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'entshifa-contracts-'));
  const liveOpenApi = path.join(tmpDir, 'openapi.json');
  const liveSchema = path.join(tmpDir, 'schema.ts');

  try {
    run('python', ['-m', 'ent.cli.export_openapi', '--out', liveOpenApi], {
      cwd: API_ROOT,
      shell: process.platform === 'win32',
    });

    const committedOpenApi = normalizeNewlines(fs.readFileSync(OPENAPI_PATH, 'utf8'));
    const actualOpenApi = normalizeNewlines(fs.readFileSync(liveOpenApi, 'utf8'));
    if (committedOpenApi !== actualOpenApi) {
      fail(
        'OpenAPI drift: FastAPI schema does not match packages/contracts/openapi.json.\n' +
          'Run `make contracts` and commit the result.',
      );
    }

    const localBin = resolveOpenapiTypescriptBin();
    if (!localBin) {
      fail(
        'openapi-typescript is not installed in packages/contracts.\n' +
          'Run: cd packages/contracts && npm install',
      );
    }
    run(process.execPath, [localBin, OPENAPI_PATH, '-o', liveSchema], {
      cwd: PACKAGE_ROOT,
    });

    const regenerated = normalizeNewlines(applyBanner(fs.readFileSync(liveSchema, 'utf8')));
    const committedSchema = normalizeNewlines(fs.readFileSync(SCHEMA_PATH, 'utf8'));
    if (committedSchema !== regenerated) {
      fail(
        'TypeScript contract drift: generated/schema.ts is out of date.\n' +
          'Run `make contracts` and commit the result.',
      );
    }

    console.log('Contract check passed: OpenAPI and TypeScript types match the API.');
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

main();
