#!/usr/bin/env node
/**
 * Generate TypeScript types from packages/contracts/openapi.json.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, '..');
const OPENAPI_PATH = path.join(PACKAGE_ROOT, 'openapi.json');
const OUT_PATH = path.join(PACKAGE_ROOT, 'generated', 'schema.ts');
const require = createRequire(import.meta.url);

const GENERATED_BANNER =
  '/**\n' +
  ' * Generated by `make contracts` from packages/contracts/openapi.json.\n' +
  ' * Do not edit by hand.\n' +
  ' */\n\n';

function resolveOpenapiTypescriptBin() {
  try {
    const pkgJson = require.resolve('openapi-typescript/package.json', {
      paths: [PACKAGE_ROOT],
    });
    const pkg = JSON.parse(fs.readFileSync(pkgJson, 'utf8'));
    const binRel = typeof pkg.bin === 'string' ? pkg.bin : pkg.bin['openapi-typescript'];
    return path.join(path.dirname(pkgJson), binRel);
  } catch {
    return null;
  }
}

function main() {
  if (!fs.existsSync(OPENAPI_PATH)) {
    console.error(`Missing ${OPENAPI_PATH}. Run: python -m ent.cli.export_openapi`);
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });

  let result;
  const localBin = resolveOpenapiTypescriptBin();
  if (localBin) {
    result = spawnSync(process.execPath, [localBin, OPENAPI_PATH, '-o', OUT_PATH], {
      cwd: PACKAGE_ROOT,
      stdio: 'inherit',
    });
  } else {
    console.error(
      'openapi-typescript is not installed. Run: cd packages/contracts && npm install',
    );
    process.exit(1);
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }

  if (!fs.existsSync(OUT_PATH)) {
    console.error(`openapi-typescript did not write ${OUT_PATH}`);
    process.exit(1);
  }

  const body = fs.readFileSync(OUT_PATH, 'utf8');
  if (!body.startsWith('/**\n * Generated by `make contracts`')) {
    fs.writeFileSync(OUT_PATH, GENERATED_BANNER + body, 'utf8');
  }

  console.log(`Wrote TypeScript types to ${OUT_PATH}`);
}

main();
